[package]
edition = "2018"
name = "what"
version = "0.1.0"
authors = ["Aram Drevekenin <aram@poor.dev>"]

[dependencies]
pnet = "0.22.0"
procfs = "0.5.3"
ipnetwork = "0.14.0"
tui = "0.5"
termion = "1.5"
structopt = "0.3"

[dev-dependencies]
assert_cmd = "0.10"
insta = "*"
cargo-insta = "*"
packet-builder = "*"
pnet_base = "*"
